### ISSUE TITLE
[2.0.9] JourneyMap 5.5.5 support

### ISSUE THREAD

**Issue by ilvrak** [Darkhax-Minecraft/JourneyMapStages#10]
![image](https://user-images.githubusercontent.com/16130834/59957172-78a59b80-94c8-11e9-85be-63f4e6f53a55.png)

**Comment by Guinaro** [comment]
Seems 5.5.5 Reimplements JourneyMap API (v1.12-1.4)

From Curseforge Page
JourneyMap 1.12.2-5.5.5 for Minecraft 1.12.2
Requirements:
    Java 8
    Minecraft 1.12.2
    Forge 14.23.5.2768

General Information:
    See http://journeymap.info/ for information about how to install and use this mod, rules about inclusion in modpacks, translation, etc.
    See http://journeymap.info/Support for information on getting technical support.
    Implements JourneyMap API v1.12-1.4

**Comment by Darkhax** [comment]
I've mentioned this a few times in other places, but basically the current version of JMapStages will intentionally only work on one specific version of JMap. This is because the mod uses hacks to accomplish some of the effects and these hacks are very easy to break when JMap updates. JMapStages was originally made using a proper API however the JMap team had to remove that API without warning. This mod was specifically made for SevTech which only needs support for a specific version range. This mod will only be updated once JMapStages has re-implemented the required APIs and is available on newer versions of Minecraft.

**Comment by mysticdrew** [comment]
> I've mentioned this a few times in other places, but basically the current version of JMapStages will intentionally only work on one specific version of JMap. This is because the mod uses hacks to accomplish some of the effects and these hacks are very easy to break when JMap updates. JMapStages was originally made using a proper API however the JMap team had to remove that API without warning. This mod was specifically made for SevTech which only needs support for a specific version range. This mod will only be updated once JMapStages has re-implemented the required APIs and is available on newer versions of Minecraft.

Sorry to resurrect this, I am not sure what happened here, was it due to the 5.6.0 update? Techbrew had RL issues happen and that version was really buggy so he pulled it. I was not around much at that time, so I am not terribly familiar with the happenings. But, I pretty much run the Journeymap show now. Soo, with that when you do decide to ever update this or want to fill me in on anything related to what you need in the api for future versions, please let me know.

**Comment by Darkhax** [comment]
> > I've mentioned this a few times in other places, but basically the current version of JMapStages will intentionally only work on one specific version of JMap. This is because the mod uses hacks to accomplish some of the effects and these hacks are very easy to break when JMap updates. JMapStages was originally made using a proper API however the JMap team had to remove that API without warning. This mod was specifically made for SevTech which only needs support for a specific version range. This mod will only be updated once JMapStages has re-implemented the required APIs and is available on newer versions of Minecraft.
> 
> Sorry to resurrect this, I am not sure what happened here, was it due to the 5.6.0 update? Techbrew had RL issues happen and that version was really buggy so he pulled it. I was not around much at that time, so I am not terribly familiar with the happenings. But, I pretty much run the Journeymap show now. Soo, with that when you do decide to ever update this or want to fill me in on anything related to what you need in the api for future versions, please let me know.

Yes I was referring to the 5.6.0 update here. Techbrew and I had been working together to get things ready for the launch of SevTech however like you mentioned some unfortunate circumstances came up. I stopped supporting 1.12 mid 2018 barring a few special exceptions like PRs. I am hoping to revisit this mod once the core of GameStages has been updated to 1.18.x, however porting has always been an uphill battle. 

I intended to merge your PR as well however I am no longer situated to build or publish for 1.12. Forge retroactively broke FG 2.3 and I've since migrated to a new CI and a modernized build pipeline. This also changed how environmental variables are loaded, and the names of most variables have changed. It's by no means impossible to get things up and running again, I am just focusing on the latest versions right now.
